### ISSUE TITLE
Bunge???

### ISSUE THREAD

**Issue by dancebunny98** [ImSouls/AdvancedReportSystem#1]
Pls work bunge!

**Comment by ImSouls** [comment]
The plugin development is currently suspended as wrote on the plugin page, you can ask for refund.
Sorry for the inconveniance

**Comment by dancebunny98** [comment]
yes.... back my money pls!

**Comment by dancebunny98** [comment]
[21:59:01 INFO]: Dancebunny98_Yt issued server command: /rps
[21:59:02 ERROR]: Could not pass event InventoryClickEvent to AdvancedReportSystem vPreRelease_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.soul.report.utils.DBS.getResult(DBS.java:116) ~[?:?]
        at me.soul.report.utils.DBS.getLocalReports(DBS.java:273) ~[?:?]
        at me.soul.report.utils.Gui.createLocalReportsListGui(Gui.java:233) ~[?:?]
        at me.soul.report.events.InvClickListener.onStaffGuiClick(InvClickListener.java:181) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        ... 15 more
[21:59:05 ERROR]: Could not pass event InventoryClickEvent to AdvancedReportSystem vPreRelease_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.soul.report.utils.DBS.getResult(DBS.java:116) ~[?:?]
        at me.soul.report.utils.DBS.getSolvedReports(DBS.java:218) ~[?:?]
        at me.soul.report.utils.Gui.createSolvedReportsGui(Gui.java:1127) ~[?:?]
        at me.soul.report.events.InvClickListener.onStaffGuiClick(InvClickListener.java:192) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        ... 15 more
[21:59:06 ERROR]: Could not pass event InventoryClickEvent to AdvancedReportSystem vPreRelease_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.soul.report.utils.DBS.getResult(DBS.java:116) ~[?:?]
        at me.soul.report.utils.DBS.getLocalReports(DBS.java:273) ~[?:?]
        at me.soul.report.utils.Gui.createLocalReportsListGui(Gui.java:233) ~[?:?]
        at me.soul.report.events.InvClickListener.onStaffGuiClick(InvClickListener.java:181) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        ... 15 more
[21:59:07 ERROR]: Could not pass event InventoryClickEvent to AdvancedReportSystem vPreRelease_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.soul.report.utils.DBS.getResult(DBS.java:116) ~[?:?]
        at me.soul.report.utils.DBS.getReports(DBS.java:205) ~[?:?]
        at me.soul.report.utils.Gui.createGlobalReportsList(Gui.java:435) ~[?:?]
        at me.soul.report.events.InvClickListener.onStaffGuiClick(InvClickListener.java:170) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        ... 15 more
[21:59:08 ERROR]: Could not pass event InventoryClickEvent to AdvancedReportSystem vPreRelease_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.soul.report.utils.DBS.getResult(DBS.java:116) ~[?:?]
        at me.soul.report.utils.DBS.getSolvedReports(DBS.java:218) ~[?:?]
        at me.soul.report.utils.Gui.createSolvedReportsGui(Gui.java:1127) ~[?:?]
        at me.soul.report.events.InvClickListener.onStaffGuiClick(InvClickListener.java:192) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        ... 15 more
[21:59:21 INFO]: Dancebunny98_Yt issued server command: /rps
[21:59:37 INFO]: Dancebunny98_Yt issued server command: /reports
[21:59:40 ERROR]: Could not pass event InventoryClickEvent to AdvancedReportSystem vPreRelease_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.soul.report.utils.DBS.getResult(DBS.java:116) ~[?:?]
        at me.soul.report.utils.DBS.getReports(DBS.java:205) ~[?:?]
        at me.soul.report.utils.Gui.createGlobalReportsList(Gui.java:435) ~[?:?]
        at me.soul.report.events.InvClickListener.onStaffGuiClick(InvClickListener.java:170) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        ... 15 more
[21:59:41 ERROR]: Could not pass event InventoryClickEvent to AdvancedReportSystem vPreRelease_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.soul.report.utils.DBS.getResult(DBS.java:116) ~[?:?]
        at me.soul.report.utils.DBS.getLocalReports(DBS.java:273) ~[?:?]
        at me.soul.report.utils.Gui.createLocalReportsListGui(Gui.java:233) ~[?:?]
        at me.soul.report.events.InvClickListener.onStaffGuiClick(InvClickListener.java:181) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        ... 15 more
[21:59:42 ERROR]: Could not pass event InventoryClickEvent to AdvancedReportSystem vPreRelease_2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.soul.report.utils.DBS.getResult(DBS.java:116) ~[?:?]
        at me.soul.report.utils.DBS.getSolvedReports(DBS.java:218) ~[?:?]
        at me.soul.report.utils.Gui.createSolvedReportsGui(Gui.java:1127) ~[?:?]
        at me.soul.report.events.InvClickListener.onStaffGuiClick(InvClickListener.java:192) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1122.jar:git-Spigot-2cf50f0-8166d17]
        ... 15 more

**Comment by ImSouls** [comment]
You can ask for refund trough paypal

**Comment by dancebunny98** [comment]
What information should I give you for a refund? How:?

**Comment by ImSouls** [comment]
I did the refund, you will get your money back.

**Comment by dancebunny98** [comment]
ok. thx
